apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: shipwright-example
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: shipwright-example
    app.kubernetes.io/part-of: shipwright-example
  name: shipwright-examplejxph
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: shipwright-example
    weight: 100
status: {}
