apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: shipwright-example
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: shipwright-example
    app.kubernetes.io/part-of: shipwright-example
  name: shipwright-example
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: shipwright-example
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: shipwright-example
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/jkhelil-tenant/shipwright-example/shipwright-example@sha256:cc3aaf971e07eaa8dcce89cf50af7623f7cddb82c83323b1d19cfade01e354d7
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
