apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: shipwright-example
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: shipwright-example
    app.kubernetes.io/part-of: shipwright-example
  name: shipwright-example
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: shipwright-example
status:
  loadBalancer: {}
